apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: apps
spec:
  interval: 1m0s
  path: ./env/dev
  prune: true
  targetNamespace: apps
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
