apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../common/flux-system
- ../../common/apps

patches:
- patch: |-
    - op: replace
      path: /spec/path
      value: ./clusters/kind-def
  target:
    kind: Kustomization
    name: flux-system