resources:
- ../../common/flux-system
- ../../common/apps/production.yaml

patches:
- patch: |-
    - op: replace
      path: /spec/path
      value: ./clusters/kind-def
  target:
    kind: Kustomization
    name: flux-system