apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-hello
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      tier: backend
      app: go-hello
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        tier: backend
        app: go-hello
    spec:
      containers:
      - name: main
        image: maliksalman/go-hello:1.0
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 50m
            memory: 32Mi
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: VER
          value: "1.0"