apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: go-hello
  namespace: apps
spec:
  interval: 1m0s
  path: ./apps/go-hello
  prune: true
  targetNamespace: apps
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
