resources:
  - ../../apps/app-a
  - ../../apps/app-b
  - ../../apps/jump
  - ../../apps/go-hello

images:
- name: maliksalman/jump
  newTag: v1.2

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 2
  target:
    kind: Deployment
