apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-b
spec:
  interval: 1m0s
  path: ./apps/app-b
  prune: true
  targetNamespace: apps
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
