apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jump
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./apps/jump
  prune: true
  targetNamespace: apps
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
